name: Tweet every 2 hour
on:
  schedule:
    - cron: '0 0,1,3,5,7,9,11,13,15,17,19,21,23 * * *'   # 13 runs, safe margin

jobs:
  tweet:
    runs-on: ubuntu-latest
    timeout-minutes: 2           # ⬅️ 2-minute hard kill

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   # needed for push-back

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Run bot
        run: node index.js
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          SERPER_KEY: ${{ secrets.SERPER_KEY }}

      - name: Persist history
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add posted.json
          git diff --staged --quiet || git commit -m "chore: update tweet history"
          git push
